modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="awakening_icarus_compat"
version="0.1.0"
displayName="Awakening Icarus Compat"
authors="xaulim"
description='''
Compatibility layer for Awakening.
Separates Faerie cosmetic Icarae wings from Icarus flight mechanics.
'''

[[mixins]]
config="awakening_icarus_compat.mixins.json"

[[dependencies.awakening_icarus_compat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.awakening_icarus_compat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.awakening_icarus_compat]]
modId="origins"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.awakening_icarus_compat]]
modId="icarus"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.awakening_icarus_compat]]
modId="icarae_origin"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"