StartupEvents.registry('item', event => {
  event.create('crude_long_sword', 'sword')
    .displayName('Crude Long Sword')
    .tier('wood')
    .attackDamageBaseline(4)
    .speedBaseline(-2.6)
    .maxDamage(64)

  event.create('crude_dagger', 'sword')
    .displayName('Crude Dagger')
    .tier('wood')
    .attackDamageBaseline(1)
    .attackDamageBonus(0.5)
    .speedBaseline(-1.5)
    .maxDamage(64)

  event.create('crude_flanged_mace', 'sword')
    .displayName('Crude Flanged Mace')
    .tier('wood')
    .attackDamageBaseline(2)
    .attackDamageBonus(0.5)
    .speedBaseline(-2.8)
    .maxDamage(64)

  event.create('crude_battleaxe', 'axe')
    .displayName('Crude Battleaxe')
    .tier('wood')
    .attackDamageBaseline(4)
    .speedBaseline(-3.0)
    .maxDamage(64)

  event.create('crude_sword', 'sword')
    .displayName('Crude Sword')
    .tier('wood')
    .attackDamageBaseline(3)
    .speedBaseline(-2.4)
    .maxDamage(64)
    .texture('minecraft:item/stone_sword')

  event.create('crude_graybeard_staff', 'sword')
    .displayName('Crude Graybeard Staff')
    .tier('wood')
    .attackDamageBaseline(1)
    .speedBaseline(-3.0)
    .maxDamage(64)
    .parentModel('irons_spellbooks:item/graybeard_staff')
    .texture('0', 'irons_spellbooks:item/graybeard_staff')
    .texture('particle', 'irons_spellbooks:item/graybeard_staff')
})
