#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 06 07:56:53 BRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
