#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Sep 08 12:50:27 BRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
