#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 11 12:27:32 BRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
