
[origins]

	[origins."origins:enderian"]
		enabled = true
		"origins:throw_ender_pearl" = true
		"origins:water_vulnerability" = true
		"origins:pumpkin_hate" = true
		"origins:extra_reach" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true

	[origins."origins:arachnid"]
		enabled = true
		"origins:climbing" = true
		"origins:master_of_webs" = true
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:blazeborn"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:damage_from_snowballs" = true
		"origins:damage_from_potions" = true

	[origins."origins:avian"]
		enabled = true
		"origins:slow_falling" = true
		"origins:fresh_air" = true
		"origins:like_air" = true
		"origins:tailwind" = true
		"origins:lay_eggs" = true
		"origins:vegetarian" = true

	[origins."origins:feline"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:sprint_jump" = true
		"origins:velvet_paws" = true
		"origins:nine_lives" = true
		"origins:weak_arms" = true
		"origins:scare_creepers" = true
		"origins:cat_vision" = true

	[origins."origins:elytrian"]
		enabled = true
		"origins:elytra" = true
		"origins:launch_into_air" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:claustrophobia" = true
		"origins:more_kinetic_damage" = true

	[origins."origins:shulk"]
		enabled = true
		"origins:shulker_inventory" = true
		"origins:natural_armor" = true
		"origins:strong_arms" = true
		"origins:strong_arms_break_speed" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true

	[origins."origins:merling"]
		enabled = true
		"origins:water_breathing" = true
		"origins:water_vision" = true
		"origins:aqua_affinity" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:aquatic" = true
		"origins:conduit_power_on_land" = true
		"origins:air_from_potions" = true

	[origins."origins:phantom"]
		enabled = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:phasing" = true
		"origins:invisibility" = true
		"origins:burn_in_daylight" = true
		"origins:hunger_over_time" = true
		"origins:fragile" = true
		"origins:phantomize_overlay" = true

	[origins."modpack_classes:barbarian"]
		enabled = true
		"modpack_classes:barbarian_rage" = true
		"modpack_classes:barbarian_combat_timer" = true
		"modpack_classes:barbarian_gain_rage_on_hit" = true
		"modpack_classes:barbarian_refresh_combat_on_hit" = true
		"modpack_classes:barbarian_gain_rage_when_hit" = true
		"modpack_classes:barbarian_refresh_combat_when_hit" = true
		"modpack_classes:barbarian_rage_decay" = true

	[origins."modpack_classes:none"]
		enabled = true

	[origins."rpgclasses:barbarian"]
		enabled = true
		"rpgclasses:barbarian_rage" = true
		"rpgclasses:barbarian_gain_rage_on_hit" = true
		"rpgclasses:barbarian_gain_rage_when_hit" = true
		"rpgclasses:barbarian/rage" = true
		"rpgclasses:barbarian/gain_rage_on_hit" = true
		"rpgclasses:barbarian/gain_rage_when_hit" = true
		"rpgclasses:barbarian/combat_timer" = true
		"rpgclasses:barbarian/rage_decay" = true
		"rpgclasses:barbarian/rage_resistance" = true
		"rpgclasses:barbarian/rage_heated" = true
		"rpgclasses:barbarian/rage_enraged" = true
		"rpgclasses:barbarian/rage_frenzy" = true
		"rpgclasses:barbarian/refresh_combat_on_hit" = true
		"rpgclasses:barbarian/pufferfish_skill_tree" = true
		"rpgclasses:barbarian/start_equipment" = true

	[origins."rpgclasses:rogue"]
		enabled = true
		"rpgclasses:rogue/start_equipment" = true
		"rpgclasses:rogue/pufferfish_skill_tree" = true

	[origins."rpgclasses:untrained"]
		enabled = true

	[origins."rpgraces:unawakened"]
		enabled = true

	[origins."rpgraces:human"]
		enabled = true
		"rpgraces:human/adaptivelearning" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgclasses:ranger"]
		enabled = true
		"rpgclasses:ranger/start_equipment" = true
		"rpgclasses:ranger/pufferfish_skill_tree" = true

	[origins."rpgclasses:warrior"]
		enabled = true
		"rpgclasses:warrior/start_equipment" = true
		"rpgclasses:warrior/pufferfish_skill_tree" = true

	[origins."rpgclasses:cleric"]
		enabled = true
		"rpgclasses:cleric/start_equipment" = true
		"rpgclasses:cleric/pufferfish_skill_tree" = true

	[origins."rpgclasses:wizard"]
		enabled = true
		"rpgclasses:wizard/start_equipment" = true
		"rpgclasses:wizard/pufferfish_skill_tree" = true

	[origins."rpgraces:woodwoad"]
		enabled = true
		"rpgclasses:woodwoad/size" = true
		"rpgraces:woodwoad/size" = true
		"rpgraces:generic/health/m4h" = true
		"rpgraces:generic/health/p4h" = true
		"rpgraces:generic/move_speed/m10p" = true
		"rpgraces:woodwoad/skin" = true
		"rpgraces:generic/resistance/p2a" = true
		"rpgraces:generic/health/p5h" = true
		"rpgraces:woodwoad/naturalregeneration" = true
		"rpgraces:woodwoad/solar_nourishment" = true
		"rpgraces:woodwoad/axe_nemesis" = true
		"rpgraces:woodwoad/flammable" = true
		"rpgraces:woodwoad/verdant_touch" = true
		"rpgraces:woodwoad/verdant_exhaustion" = true
		"rpgraces:woodwoad/exhaustion_effects" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:myconid"]
		enabled = true
		"rpgraces:myconid/size" = true
		"rpgraces:myconid/shrink" = true
		"rpgraces:myconid/grow" = true
		"rpgraces:myconid/form_state" = true
		"rpgraces:myconid/size_lifecycles" = true
		"rpgraces:generic/health/m2h" = true
		"rpgraces:myconid/compact_mechanics" = true
		"rpgraces:myconid/bloomed_mechanics" = true
		"rpgraces:generic/move_speed/m5p" = true
		"rpgraces:generic/dark_vision/common" = true
		"rpgraces:myconid/fungalbody" = true
		"rpgraces:myconid/natural_mechanics" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:ravenfolk"]
		enabled = true
		"rpgclasses:ravenfolk/size" = true
		"rpgraces:ravenfolk/size" = true
		"rpgraces:generic/health/m2h" = true
		"rpgraces:ravenfolk/wings" = true
		"rpgraces:ravenfolk/flimsy" = true
		"rpgraces:generic/feather_fall/m50p" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:frogfolk"]
		enabled = true
		"rpgclasses:frogfolk/size" = true
		"rpgraces:frogfolk/size" = true
		"rpgraces:frogfolk/froghop" = true
		"rpgraces:frogfolk/softlanding" = true
		"rpgraces:generic/feather_fall/m25p" = true
		"rpgraces:generic/swim_speed/p50p" = true
		"rpgraces:frogfolk/skin" = true
		"rpgraces:frogfolk/super_jump" = true
		"rpgraces:frogfolk/moisture_dry_normal" = true
		"rpgraces:frogfolk/moisture_dry_humid" = true
		"rpgraces:frogfolk/moisture_dry_hot" = true
		"rpgraces:frogfolk/moisture_rain" = true
		"rpgraces:frogfolk/moisture_water" = true
		"rpgraces:frogfolk/moisture" = true
		"rpgraces:frogfolk/hydrated" = true
		"rpgraces:frogfolk/dry" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:giantborn"]
		enabled = true
		"rpgclasses:giantborn/size" = true
		"rpgraces:giantborn/size" = true
		"rpgraces:generic/health/p3h" = true
		"rpgraces:giantborn/change_size" = true
		"rpgraces:giantborn/size_lifecycles" = true
		"rpgraces:giantborn/form_state" = true
		"rpgraces:giantborn/released_mechanics" = true
		"rpgraces:generic/move_speed/m5p" = true
		"rpgraces:generic/metabolism/p30p" = true
		"rpgraces:generic/feather_fall/p10p" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:feline"]
		enabled = true
		"rpgclasses:feline/size" = true
		"rpgraces:feline/size" = true
		"rpgraces:generic/health/m2h" = true
		"rpgraces:feline/move_speed" = true
		"rpgraces:feline/increased_metabolism" = true
		"rpgraces:generic/move_speed/p15p" = true
		"rpgraces:generic/metabolism/p30p" = true
		"rpgraces:generic/dark_vision/common" = true
		"rpgraces:generic/feather_fall/m75p" = true
		"rpgraces:feline/catjump" = true
		"rpgraces:feline/softlanding" = true
		"rpgraces:feline/sprintjump" = true
		"origins:scare_creepers" = true
		"rpgraces:feline/velvet_paws" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:elf"]
		enabled = true
		"rpgraces:elf/size" = true
		"rpgraces:generic/move_speed/p5p" = true
		"rpgraces:generic/feather_fall/m25p" = true
		"rpgraces:elf/elf_finesse" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:orc"]
		enabled = true
		"rpgclasses:orc/size" = true
		"rpgraces:orc/size" = true
		"rpgraces:generic/health/p2h" = true
		"rpgraces:generic/metabolism/p20p" = true
		"rpgraces:orc/skin" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:faerie"]
		enabled = true
		"rpgraces:faerie/set_scale" = true
		"rpgraces:faerie/set_fly" = true
		"rpgraces:faerie/size" = true
		"rpgraces:generic/health/m5h" = true
		"rpgraces:generic/move_speed/p5p" = true
		"rpgraces:faerie/wings" = true
		"rpgraces:faerie/flimsy" = true
		"rpgraces:faerie/fly" = true
		"rpgraces:faerie/flightless_wings" = true
		"rpgraces:arcaneskin" = true
		"rpgraces:faerie/faerieparticles" = true
		"rpgraces:faerie/arcaneskin" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:dwarf"]
		enabled = true
		"rpgraces:dwarf/size" = true
		"rpgraces:generic/move_speed/m5p" = true
		"rpgraces:generic/dark_vision/common" = true
		"rpgraces:dwarf/dwarven_mining" = true
		"rpgraces:generic/metabolism/p20p" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:tortle"]
		enabled = true
		"rpgclasses:tortle/size" = true
		"rpgraces:tortle/size" = true
		"rpgraces:generic/health/p2h" = true
		"rpgraces:generic/move_speed/m10p" = true
		"origins:aquatic" = true
		"rpgraces:generic/swim_speed/p50p" = true
		"rpgraces:tortle/skin" = true
		"origins:aqua_affinity" = true
		"rpgraces:generic/resistance/p2a" = true
		"rpgraces:generic/resistance/p4a" = true
		"rpgraces:tortle/holdbreath" = true
		"rpgraces:generic/swim_speed/p25p" = true
		"rpgraces:generic/move_speed/m15p" = true
		"rpgraces:tortle/shellarmor" = true
		"rpgraces:generic/feather_fall/p10p" = true
		"rpgraces:tortle/shell_state" = true
		"rpgraces:tortle/shell_cooldown" = true
		"rpgraces:tortle/shell_activate" = true
		"rpgraces:tortle/shell_timer" = true
		"rpgraces:tortle/shell_defense" = true
		"rpgraces:tortle/shell_immobility" = true
		"rpgraces:tortle/shell_no_jump" = true
		"rpgraces:tortle/shell_no_attack" = true
		"rpgraces:tortle/shell_no_item_use" = true
		"rpgraces:tortle/shell_no_block_use" = true
		"rpgraces:tortle/shell_no_entity_use" = true
		"rpgraces:tortle/shell_no_sprint" = true
		"rpgraces:tortle/shell_reset" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:dragonborn"]
		enabled = true
		"rpgraces:dragonborn/size" = true
		"rpgraces:generic/metanbolism/p10p" = true
		"rpgraces:generic/metabolism/p10p" = true
		"rpgraces:meta/race_selected" = true

	[origins."rpgraces:lineage/dragonborn/ice"]
		enabled = true
		"rpgraces:dragonborn/ice/skin" = true
		"rpgraces:dragonborn/ice/lineage_marker" = true
		"rpgraces:dragonborn/ice/glacier_skin" = true
		"rpgraces:dragonborn/thermal_affinity" = true
		"rpgraces:dragonborn/thermal_strain" = true
		"rpgraces:dragonborn/ice/breath" = true
		"rpgraces:dragonborn/ice/breath_cooldown" = true
		"rpgraces:dragonborn/ice/ice_magic_resistence" = true

	[origins."rpgraces:lineage/elf/drow"]
		enabled = true
		"rpgraces:elf/drow_size" = true
		"rpgraces:generic/dark_vision/superior" = true
		"rpgraces:elf/drow/skin" = true
		"rpgraces:elf/drow/sun_sensitivity" = true
		"rpgraces:elf/drow/shadow_veil" = true

	[origins."rpgraces:lineage/elf/highelf"]
		enabled = true

	[origins."rpgraces:lineage/dragonborn/lighting"]
		enabled = true

	[origins."rpgraces:lineage/dragonborn/fire"]
		enabled = true
		"rpgraces:dragonborn/fire/skin" = true
		"rpgraces:dragonborn/fire/lineage_marker" = true
		"rpgraces:dragonborn/fire/fireresistence" = true
		"rpgraces:dragonborn/fire/thermal_affinity" = true
		"rpgraces:dragonborn/fire/thermal_strain" = true
		"rpgraces:dragonborn/fire/magma_walker" = true
		"rpgraces:dragonborn/thermal_affinity" = true
		"rpgraces:dragonborn/thermal_strain" = true
		"rpgraces:dragonborn/fire/breath" = true
		"rpgraces:dragonborn/fire/breath_cooldown" = true
		"rpgraces:dragonborn/fire/fire_magic_resistence" = true

	[origins."rpgraces:lineage/dwarf/mountaindwarf"]
		enabled = true

	[origins."rpgraces:lineage/elf/woodelf"]
		enabled = true

	[origins."rpgraces:lineage/dwarf/hilldwarf"]
		enabled = true

	[origins."rpgraces:lineage/dwarf/hill"]
		enabled = true
		"rpgraces:generic/health/p2h" = true
		"rpgraces:dwarf/hill/strongblood" = true
		"rpgraces:dwarf/hill/ancestral_wisdom" = true

	[origins."rpgraces:lineage/elf/high"]
		enabled = true
		"rpgraces:elf/high_size" = true
		"rpgraces:elf/high_elf/size" = true
		"rpgraces:generic/dark_vision/common" = true
		"rpgraces:elf/high_elf/arcane_affinity" = true

	[origins."rpgraces:lineage/dwarf/mountain"]
		enabled = true
		"rpgraces:dwarf/mountain/stone_sense" = true
		"rpgraces:dwarf/mountain/armored_heritage" = true
		"rpgraces:dwarf/mountain/mountains_roots" = true

	[origins."rpgraces:lineage/elf/wood"]
		enabled = true
		"rpgraces:elf/wood_size" = true
		"rpgraces:elf/wood_elf/wood_elf_speed" = true
		"rpgraces:generic/dark_vision/common" = true
		"rpgraces:elf/wood_elf/forest_veil" = true

	[origins."rpgraces:lineage/dragonborn/lightning"]
		enabled = true
		"rpgraces:dragonborn/lightning/skin" = true
		"rpgraces:dragonborn/lightning/lineage_marker" = true
		"rpgraces:dragonborn/lightning/galvanized" = true
		"rpgraces:dragonborn/lightning/storm_sense" = true
		"rpgraces:dragonborn/lightning/lightning_conductor" = true
		"rpgraces:dragonborn/lightning/breath" = true
		"rpgraces:dragonborn/lightning/breath_cooldown" = true
		"rpgraces:dragonborn/lightning/lightning_magic_resistence" = true

	[origins."icarae_origin:icarae"]
		enabled = true
		"icarae_origin:wings" = true
		"origins:aerial_combatant" = true
		"icarae_origin:icarus" = true
		"icarae_origin:hollow_bones" = true
		"icarae_origin:flimsy" = true
		"origins:carnivore" = true

	[origins."rpgclasses:paladin"]
		enabled = true
		"rpgclasses:paladin/start_equipment" = true
		"rpgclasses:paladin/pufferfish_skill_tree" = true

