modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="awakening_compat"
version="${file.jarVersion}"
displayName="Awakening Compat"
authors="Xaulim"
description='''
Mod de compatibilidade e mecânicas customizadas do modpack Awakening.
Inclui integrações com Icarus, Iron's Spells 'n Spellbooks e outros mods.
'''

# =========================
# FORGE
# =========================

[[dependencies.awakening_compat]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="BOTH"

# =========================
# MINECRAFT
# =========================

[[dependencies.awakening_compat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

# =========================
# ORIGINS
# =========================

[[dependencies.awakening_compat]]
modId="origins"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

# =========================
# ICARUS
# =========================

[[dependencies.awakening_compat]]
modId="icarus"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"

# =========================
# IRON'S SPELLBOOKS
# =========================

[[dependencies.awakening_compat]]
modId="irons_spellbooks"
mandatory=true
versionRange="[1.20.1-3.16.3,1.20.1-3.17.0)"
ordering="AFTER"
side="BOTH"